# Generated by Django 4.1.7 on 2023-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt_keyword', models.CharField(max_length=256)),
                ('cmt_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=64)),
                ('website_authentication', models.TextField(max_length=64)),
                ('number_of_comments', models.IntegerField()),
                ('number_of_shares', models.IntegerField()),
                ('number_of_likes', models.IntegerField()),
                ('source_platform', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CommentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=256)),
                ('img_text', models.TextField()),
            ],
        ),
    ]
