# Generated by Django 4.1.7 on 2023-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgptcomments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QAmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
